"""
Export Service.
Generates downloadable files in Markdown, Plain Text, HTML, JSON, and PowerPoint (.pptx).
"""

import io
import json
from typing import Dict, Any, List

def generate_markdown_export(job_title: str, outputs: List[Dict[str, Any]]) -> str:
    """Generates a master Markdown report containing all generated transformations."""
    md = f"# Transformation Report: {job_title}\n"
    md += f"*Generated by Gen AI Content Repurposing Platform*\n\n"
    md += f"---\n\n"
    
    for item in outputs:
        fmt = item.get("output_type", "Output").upper()
        title = item.get("title", fmt)
        content = item.get("content_markdown", "")
        md += f"## [{fmt}] {title}\n\n"
        md += f"{content}\n\n"
        md += f"---\n\n"
        
    return md

def generate_html_export(job_title: str, outputs: List[Dict[str, Any]]) -> str:
    """Generates a beautifully styled, printable HTML document."""
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TransformAI: {job_title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: #1e293b;
            max-width: 900px;
            margin: 40px auto;
            padding: 0 20px;
            background-color: #f8fafc;
        }}
        .header {{
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 24px;
            margin-bottom: 32px;
        }}
        .header h1 {{
            color: #0f172a;
            margin-bottom: 8px;
            font-size: 28px;
        }}
        .badge {{
            display: inline-block;
            background: #e0e7ff;
            color: #4338ca;
            padding: 4px 12px;
            border-radius: 9999px;
            font-weight: 600;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}
        .card {{
            background: #ffffff;
            border-radius: 12px;
            border: 1px solid #e2e8f0;
            padding: 28px;
            margin-bottom: 28px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        }}
        .card-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #f1f5f9;
            padding-bottom: 16px;
            margin-bottom: 20px;
        }}
        .card-title {{
            font-size: 20px;
            font-weight: 700;
            color: #0f172a;
            margin: 0;
        }}
        pre {{
            background: #f1f5f9;
            padding: 16px;
            border-radius: 8px;
            overflow-x: auto;
            white-space: pre-wrap;
            font-family: inherit;
        }}
        @media print {{
            body {{ background: white; }}
            .card {{ box-shadow: none; border: 1px solid #ccc; page-break-inside: avoid; }}
        }}
    </style>
</head>
<body>
    <div class="header">
        <span class="badge">Gen AI Repurposed Content</span>
        <h1>{job_title}</h1>
        <p style="color: #64748b; margin: 4px 0 0 0;">Autonomous Multi-Format Transformation Synthesis Report</p>
    </div>
"""
    for item in outputs:
        fmt = item.get("output_type", "Output").upper()
        title = item.get("title", fmt)
        content = item.get("content_markdown", "")
        # Escape simple html
        escaped_content = content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        html += f"""
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">{title}</h2>
            <span class="badge">{fmt}</span>
        </div>
        <pre>{escaped_content}</pre>
    </div>
"""
    html += """
</body>
</html>"""
    return html

def generate_powerpoint_presentation(presentation_data: Dict[str, Any]) -> io.BytesIO:
    """
    Builds a real PowerPoint (.pptx) file using python-pptx from structured presentation slides.
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        
        prs = Presentation()
        # Set 16:9 slide width/height
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)
        
        slides_list = presentation_data.get("slides", [])
        
        # Color palette
        INDIGO = RGBColor(79, 70, 229)
        DARK_SLATE = RGBColor(15, 23, 42)
        MUTED_GRAY = RGBColor(100, 116, 139)
        WHITE = RGBColor(255, 255, 255)
        
        blank_slide_layout = prs.slide_layouts[6]
        
        for slide_info in slides_list:
            slide = prs.slides.add_slide(blank_slide_layout)
            
            # Slide Title
            title_box = slide.shapes.add_textbox(Inches(1.0), Inches(0.8), Inches(11.333), Inches(1.2))
            tf = title_box.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = slide_info.get("title", "Slide Title")
            p.font.size = Pt(36)
            p.font.bold = True
            p.font.color.rgb = INDIGO
            
            # Bullets
            content_box = slide.shapes.add_textbox(Inches(1.0), Inches(2.2), Inches(11.333), Inches(3.8))
            ctf = content_box.text_frame
            ctf.word_wrap = True
            
            bullets = slide_info.get("bullets", [])
            for i, bullet_text in enumerate(bullets):
                bp = ctf.paragraphs[0] if i == 0 else ctf.add_paragraph()
                bp.text = f"•  {bullet_text}"
                bp.font.size = Pt(22)
                bp.font.color.rgb = DARK_SLATE
                bp.space_after = Pt(14)
            
            # Speaker notes & visual cue footer
            notes = slide_info.get("speaker_notes", "")
            if notes:
                footer_box = slide.shapes.add_textbox(Inches(1.0), Inches(6.2), Inches(11.333), Inches(0.8))
                ftf = footer_box.text_frame
                ftf.word_wrap = True
                fp = ftf.paragraphs[0]
                fp.text = f"Presenter Note: {notes}"
                fp.font.size = Pt(13)
                fp.font.italic = True
                fp.font.color.rgb = MUTED_GRAY
                
        output_stream = io.BytesIO()
        prs.save(output_stream)
        output_stream.seek(0)
        return output_stream
    except Exception as e:
        print(f"[PPTX Generation Error]: {e}")
        return io.BytesIO()
